version: '3.8'

services:
  redis:
    image: redis:6.2.6
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data
  rabbitmq:
    image: rabbitmq:3.11.14-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
        # - ./rhome/data/:/var/lib/rabbitmq/
        # - ./rhome/log/:/var/log/rabbitmq/
        - ./conf/enabled_plugins:/etc/rabbitmq/enabled_plugins  
  webapp:
    image: webapp:1
    # build: ./web
      # context: ./web
      # dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - ACELERY_BROKER=amqp://guest@rabbitmq//
      - ACELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - rabbitmq
  flower:
    image: mher/flower:1.2
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq//
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq
      - redis
  taskapp1:
    image: taskapp:1
    container_name: joe
    # build: ./tasks
      # context: ./web
      # dockerfile: Dockerfile
    # ports:
      # - 8000:8000
    environment:
      - ACELERY_BROKER=amqp://guest:guest@rabbitmq:5672//
      - ACELERY_BACKEND=redis://redis:6379/0
      - ACUDA_CORE="cuda:0"
    depends_on:
      - rabbitmq
      - redis
  taskapp2:
    image: taskapp:1
    container_name: bob
    # build: ./tasks
      # context: ./web
      # dockerfile: Dockerfile
    # ports:
      # - 8000:8000
    environment:
      - ACELERY_BROKER=amqp://guest:guest@rabbitmq:5672//
      - ACELERY_BACKEND=redis://redis:6379/0
      - ACUDA_CORE="cuda:1"
    depends_on:
      - rabbitmq
      - redis